#!/bin/bash

# --                                                            ; {{{1
#
# File        : srvbak
# Maintainer  : Felix C. Stegerman <flx@obfusk.net>
# Date        : 2013-03-12
#
# Copyright   : Copyright (C) 2013  Felix C. Stegerman
# Licence     : GPLv2
#
# --                                                            ; }}}1

source "$1" || exit 1

date="$( date +'%FT%T' )"

function run () { echo "==> $@"; "$@"; echo; }
function run_multi () { local x; for x in "$@"; do run $x; done; }

function process_mongo_passfile ()
{                                                               # {{{1
  local oldifs="$IFS" db user pass
  IFS=:
  while read -r db user pass; do
    [[ "$db" =~ ^[A-Za-z0-9]+$ ]] || exit 1
    eval "mongo_auth__${db}__user=\$user"
    eval "mongo_auth__${db}__pass=\$pass"
  done < "$mongo_passfile"
  IFS="$oldifs"
}                                                               # }}}1

function pg_backup ()
{                                                               # {{{1
  local dbname="$1"
  local dir="$base_dir"/postgresql/"$dbname"
  local dump="$dir/$date".sql

  mkdir -p "$dir"
  run pg_dump "$dbname" -f "$dump" -w
}                                                               # }}}1

function mongo_backup ()
{                                                               # {{{1
  local dbname="$1" user pass
  local dir="$base_dir"/mongodb/"$dbname"
  local dump="$dir/$date"

  [[ "$dbname" =~ ^[A-Za-z0-9]+$ ]] || exit 1
  eval "user=\$mongo_auth__${dbname}__user"
  eval "pass=\$mongo_auth__${dbname}__pass"

  mkdir -p "$dir"
  echo "$pass" | run mongodump -h "$mongo_host" -d "$dbname" \
    -u "$user" -p '' -o "$dump"
}                                                               # }}}1

function data_backup ()
{                                                               # {{{1
  local dir="$1"
  local to="$base_dir"/data/"$dir"/"$date"

  mkdir -p "$to"
  run rsync -a --delete "$dir"/ "$to"/
}                                                               # }}}1

# --

# 1. stop services
run_multi "${services_stop[@]}"

# 2. baktogit
[ "${#baktogit_items[@]}" -ne 0 ] && \
  run "$baktogit" "${baktogit_items[@]}"

# 3. postgresql
for db in "${postgresql_dbs[@]}"; do pg_backup "$db"; done

# 4. mongodb
[ "${#mongo_dbs[@]}" -ne 0 ] && process_mongo_passfile
for db in "${mongo_dbs[@]}"; do mongo_backup "$db"; done

# 5. data
for dir in "${data_dirs[@]}"; do data_backup "$dir"; done

# 6. start services
run_multi "${services_start[@]}"

# 7. copy backup to remote location(s)
# ... TODO ...

# vim: set tw=70 sw=2 sts=2 et fdm=marker :
